exp_name: 'pred_modelinfo_datainfo'
save_path: '/home/yw24267/work/DLFF/preds'
remarks: "prediction of what model on what data"
device: 'cuda'  # make it consistent throughout all codes. gpu index or cuda/cpu
# backup: ['code', 'config']  # not yet implemented

predict:
  model_ckpt: '/work/yw24267/DLFF/runs/posout_d611_rand_20220616-183435/models/Checkpoint_Epoch29_2.97_20220618-073524.pt'
  csv_path: '/work/yw24267/DLFF/data/ANI1/for_training/test/test.csv'
  label_column: 'LABEL_E_covalent'
  pred_column: 'PRED_E_covalent'
  loading_workers: 0
  batch_size: 200
  dataset_name: "SPICE"
  h5_files: [
    '/scratch/yw_data/DLFF/data/ANI1/ANI-1_release/ani_gdb_s01.h5',
    '/scratch/yw_data/DLFF/data/ANI1/ANI-1_release/ani_gdb_s02.h5',
    '/scratch/yw_data/DLFF/data/ANI1/ANI-1_release/ani_gdb_s03.h5',
    '/scratch/yw_data/DLFF/data/ANI1/ANI-1_release/ani_gdb_s04.h5',
    '/scratch/yw_data/DLFF/data/ANI1/ANI-1_release/ani_gdb_s05.h5',
    '/scratch/yw_data/DLFF/data/ANI1/ANI-1_release/ani_gdb_s06.h5',
    '/scratch/yw_data/DLFF/data/ANI1/ANI-1_release/ani_gdb_s07.h5',
    '/scratch/yw_data/DLFF/data/ANI1/ANI-1_release/ani_gdb_s08.h5'
  ]  # store xyz data
  h5_multipole: "/home/yw24267/work/DLFF/data/ANI1/ANI-1_multipoles.h5"
